name: Deploy DEV

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out dev branch
        run: git checkout dev
      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm run install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Upload dist directory to the server using scp
      - name: Deploy Build Artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./dist
          target: /srv/pwa
